version: '3'

services:
  pulsar:
    image: 'apachepulsar/pulsar:2.11.0'
    command: 'bin/pulsar standalone'
    ports:
      - '6650:6650'
      - '8080:8080'
    volumes:
      - 'pulsardata:/pulsar/data'
      - 'pulsarconf:/pulsar/conf'

volumes:
  pulsardata:
  pulsarconf:
